### PR TITLE
enabled serviceMonitor

### PR DESCRIPTION
**Pull request by QuantumEnigmaa**
towards https://github.com/giantswarm/roadmap/issues/722

In order for promtail to be scraped by prometheus on every MC, need to enable serviceMonitor.

### CODE REVIEW

**Comment by QuantumEnigmaa** [comment]
As promtail-app is only deployed on Gorilla which is not a testing installation, could we deploy it on a testing installation or should I test it on Gorilla nonetheless ?

**Review by QuentinBisson — APPROVED** [review]

**Comment by QuentinBisson** [comment]
Should we kickstart this @QuantumEnigmaa ?

**Comment by QuantumEnigmaa** [comment]
I think we should better test it with @hervenicol once we are finished installing Loki on gauss the right way (not manually as we did)

**Comment by hervenicol** [comment]
Well, except if we want to include promtail in o11y-bundle we should hurry up with including base features like monitoring.
But, promtail will be deployed on MCs and WCs. And not all WCs support servicemonitor. Not sure that should be the default way of monitoring it yet.

**Comment by QuantumEnigmaa** [comment]
In any case, the base monitoring using giantswarm labels is currently working for promtail : https://github.com/giantswarm/promtail-app/pull/74

**Comment by QuentinBisson** [comment]
If we enable service monitors in a New release and use that in the o11y bundle then we are fine because those support service monitors

**Comment by QuentinBisson** [comment]
But then if we enable service monitors we need to remove labels

**Comment by QuantumEnigmaa** [comment]
I think this PR is now relevant with recent changes :)

**Comment by QuentinBisson** [comment]
Well, yes and no because it depends if the bundle is deployed or not :(

**Pull request closed without merging**
